using System.Collections;
using System.Globalization;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace TexasHoldem
{
    /// <summary>
    /// Displays a player's current round bet as a PokerStars-style chip stack + amount badge.
    /// Layout (managed by PlayerSeatLayout):
    ///   BetDisplay root
    ///   ├── ChipStack   — 3 stacked poker chip Images offset to fake depth
    ///   └── AmountBadge — dark rounded pill with bold euro text
    ///
    /// When the bet increases, a chip graphic flies from the player's avatar to ChipStack.
    /// Managed entirely by UIManager — never show or hide this from game logic directly.
    /// </summary>
    public class BetDisplay : MonoBehaviour
    {
        // Platform-independent German number format: 1000 → "1.000"
        private static readonly NumberFormatInfo GermanNFI = new NumberFormatInfo
        {
            NumberGroupSeparator   = ".",
            NumberDecimalSeparator = ",",
            NumberDecimalDigits    = 0,
            NumberGroupSizes       = new[] { 3 }
        };

        [SerializeField] private TMP_Text      _amountText;
        [SerializeField] private RectTransform _chipStackRoot; // animation fly-to target

        private const float AnimDuration = 0.45f;
        private const float ChipAnimSize = 34f;

        private static readonly AnimationCurve EaseCurve =
            AnimationCurve.EaseInOut(0f, 0f, 1f, 1f);

        // Matches the green chip sprite colour generated by PlayerSeatLayout.
        private static readonly Color ChipAnimColor = new Color(0.12f, 0.42f, 0.19f, 1f);

        private Canvas    _rootCanvas;
        private Coroutine _chipCoroutine;

        private void Awake()
        {
            Canvas c = GetComponentInParent<Canvas>();
            while (c != null && !c.isRootCanvas)
                c = c.transform.parent != null
                    ? c.transform.parent.GetComponentInParent<Canvas>()
                    : null;
            _rootCanvas = c;
        }

        /// <summary>
        /// Activates the display and shows <paramref name="amount"/>.
        /// Pass <paramref name="fromRect"/> to trigger a chip flying from that position.
        /// </summary>
        public void ShowBet(int amount, RectTransform fromRect = null)
        {
            if (_amountText != null)
                _amountText.text = amount.ToString("N0", GermanNFI) + " \u20AC";

            gameObject.SetActive(true);

            if (fromRect != null && _rootCanvas != null)
            {
                if (_chipCoroutine != null) StopCoroutine(_chipCoroutine);
                _chipCoroutine = StartCoroutine(AnimateChip(fromRect));
            }
        }

        /// <summary>Hides the display and cancels any in-progress chip animation.</summary>
        public void HideBet()
        {
            if (_chipCoroutine != null)
            {
                StopCoroutine(_chipCoroutine);
                _chipCoroutine = null;
            }
            gameObject.SetActive(false);
        }

        private IEnumerator AnimateChip(RectTransform origin)
        {
            // Target is the chip stack centre so the flying chip lands on the stack.
            RectTransform target = _chipStackRoot != null
                ? _chipStackRoot
                : (RectTransform)transform;

            // Spawn a temporary chip on the root canvas so it renders above all seat
            // panels and is never clipped by a Mask component.
            var chipGo  = new GameObject("_ChipAnim", typeof(RectTransform), typeof(Image));
            var chipImg = chipGo.GetComponent<Image>();
            chipImg.sprite        = null;
            chipImg.color         = ChipAnimColor;
            chipImg.raycastTarget = false;

            var chipRt = (RectTransform)chipGo.transform;
            chipRt.SetParent((RectTransform)_rootCanvas.transform, false);
            chipRt.sizeDelta  = new Vector2(ChipAnimSize, ChipAnimSize);
            chipRt.anchorMin  = new Vector2(0.5f, 0.5f);
            chipRt.anchorMax  = new Vector2(0.5f, 0.5f);
            chipRt.pivot      = new Vector2(0.5f, 0.5f);

            Vector2 startPos        = ToCanvasLocal(origin);
            Vector2 endPos          = ToCanvasLocal(target);
            chipRt.anchoredPosition = startPos;

            float elapsed = 0f;
            while (elapsed < AnimDuration)
            {
                elapsed += Time.deltaTime;
                float t = EaseCurve.Evaluate(Mathf.Clamp01(elapsed / AnimDuration));
                chipRt.anchoredPosition = Vector2.Lerp(startPos, endPos, t);
                chipRt.localScale       = Vector3.Lerp(Vector3.one * 1.4f, Vector3.one * 0.8f, t);
                chipImg.color = new Color(
                    ChipAnimColor.r, ChipAnimColor.g, ChipAnimColor.b,
                    Mathf.Lerp(1f, 0f, t * t));
                yield return null;
            }

            if (chipGo != null) Destroy(chipGo);
            _chipCoroutine = null;
        }

        /// <summary>Converts a RectTransform's pivot to the root canvas's local space.</summary>
        private Vector2 ToCanvasLocal(RectTransform rt)
        {
            var canvasRt = (RectTransform)_rootCanvas.transform;
            return canvasRt.InverseTransformPoint(rt.TransformPoint(Vector3.zero));
        }
    }
}
